version: '3.8'

services:
  # MariaDB para o banco de dados principal
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    container_name: mariadb_container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: school_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    networks:
      - monitoring

  # Aplicação Flask
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    container_name: flask_app_container
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DB_HOST: mariadb
      FLASK_DB_USER: flask_user
      FLASK_DB_PASSWORD: flask_password
      FLASK_DB_NAME: school_db
    networks:
      - monitoring

  # mysqld_exporter para coletar métricas do MariaDB
  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    environment:
      DATA_SOURCE_NAME: flask_user:flask_password@(mariadb:3306)/school_db
    networks:
      - monitoring
    depends_on:
      - mariadb
    ports:
      - "9104:9104"  # Porta padrão do mysqld_exporter

  # Prometheus para coletar métricas do mysqld_exporter e outros serviços
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - "9090:9090"

  # Grafana para visualizar as métricas coletadas pelo Prometheus
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  db_data:
